FROM public.ecr.aws/lambda/python:3.9

# Install required Python packages
RUN pip3 install pandas && \
    pip3 install numpy && \
    pip3 install boto3 && \
    pip3 install scikit-learn && \
    pip3 install xgboost==1.6.1

# Enable Lambda Insights
RUN curl -O https://lambda-insights-extension.s3-ap-northeast-1.amazonaws.com/amazon_linux/lambda-insights-extension.rpm && \
    rpm -U lambda-insights-extension.rpm && \
    rm -f lambda-insights-extension.rpm

# Copy model artifacts and Lambda function code
COPY processing.py ${LAMBDA_TASK_ROOT}
COPY sample_model.json ${LAMBDA_TASK_ROOT}

CMD [ "processing.handler" ]